### ISSUE TITLE
toDo

### ISSUE THREAD

**Issue by Nowosad** [eRum2016/Book-of-abstracts#7]
- [x] w planie na stronie iii-v oddzielić sesje poziomymi liniami (jak tylko program będzie pewny)
- [x] indeks autorów
- [x] indeks pakietów
- [x] tylna okładka - @MarcinKosinski @pedzlenie

**Comment by BERENZ** [comment]
@Nowosad proponuję 
- [x] pustą stronę po stronie tytułowej
- [x] rozpoczęcie nowej sekcji od strony parzystej  (np. komitet organizacyjny)
- [x] kod QR o programie poniżej tabeli
- [x] czy da się wszystkie abstrakty wyjustować ? 
- [x] jak rozpoczyna się sekcja z sesją proszę o dodanie sali oraz prowadzącego sesję

**Comment by Nowosad** [comment]
Done and done.

**Comment by BERENZ** [comment]
@Nowosad proszę dodaj jeszcze do warsztatów podział na poranne i popołudniowe wraz z godziną

**Comment by Nowosad** [comment]
Done.
